### ISSUE TITLE
Query doesn't support empty array

### ISSUE THREAD

**Issue by ZachRoberts25** [travetto/travetto#28]
**Describe the bug**
The query syntax for `$in` doesn't support passing in an empty array.  It attempts to look in the array for the type, and fails when it doesn't find the first value in the array.

**To Reproduce**
`{where: { id: { $in: [] } } }`

**Expected behavior**
If you ask for an query with $in set to empty array, the query should just return nothing.  This prevents end users from having to handle empty arrays specially.

**Comment by arciisine** [comment]
I think this could be a dangerous precedent, given the inverse of using `$nin`.  Not executing the query when ids are missing, makes sense, but I'm not sure if I should return or throw an error.  Thinking of the other operators, an error is potentially desirable.

**Comment by ZachRoberts25** [comment]
Maybe a more expressive error message, or support passing in [].  I hear you on setting a precedent, so I think at least, show an error that says this type of query is unsupported.  I can set up a PR for the error message if you like

**Comment by arciisine** [comment]
Sounds like a plan, I should have a fix out today or tomorrow.

**Comment by arciisine** [comment]
This should also be fixed in `0.7.1-alpha.1`.
