### ISSUE TITLE
Rest doesn't support Map

### ISSUE THREAD

**Issue by ZachRoberts25** [travetto/travetto#31]
When returning a Javascript `Map` from a controller function, Travetto returns an empty object.  We should convert the map to JSON properly.  Let me know if this works/makes sense for you.
```[...res.insertedIds.entries()].reduce((main, [key, value]) => ({ ...main, [key]: value }), {})```

**Comment by arciisine** [comment]
I'm assuming you mean the `Map` class specifically.  This would most likely apply to `Set` as well.  I can take a look at it.  I have a 0.7.1-alpha release set where all of this is being released, I'll push out a fix tonight.

**Comment by arciisine** [comment]
Pushed as `0.7.1-alpha.1`, give it a go and let me know if it fits the bill.

**Comment by ZachRoberts25** [comment]
Closing as fixed
