### ISSUE TITLE
ModelStore is not good with Mongodb

### ISSUE THREAD

**Issue by ZachRoberts25** [travetto/travetto#32]
```id: Util.uuid()``` in session store.  Mongo doesn't like this as an id, it throws this error
Argument passed in must be a single String of 12 bytes

```id: Util.uuid(12)``` fixes the problem.  Let me know if this works for you and I'll open up a PR

**Comment by arciisine** [comment]
This is in the 0.7.1-alpha release I'm assuming?

**Comment by arciisine** [comment]
Should be fixed in the latest 0.6.x release.
