### ISSUE TITLE
Unknown command run in Windows

### ISSUE THREAD

**Issue by Enchiphobe** [travetto/travetto#34]
When trying to run a Travetto app on Windows, get error: 
`[@trv:cli/util: 89] Unknown command run`

**To Reproduce**
1. Use Yeoman generator to a new Travetto app on Windows.
2. `npm start` or `npx travetto run`

**Expected behavior**
Should start the app on localhost:3000

**Additional context**
I've confirmed global installation of Travetto CLI and that @travetto/cli is included in the project's node modules. The issue occurs with both, either, or neither of those two cli installations. 

additionally, while in a Travetto project, `travetto --version` and `travetto --help` produce errors in both PC and Mac.

**Comment by arciisine** [comment]
Hmm, I'll take a look, it seems to be a path issue, and the global state shouldn't cause any issues.  What version of node are you running?

**Comment by Enchiphobe** [comment]
10.16.0

**Comment by arciisine** [comment]
Thanks for the report, there seems to be something off on windows on how it deploys bin files.  It was working at one point, I should have a fix out soon.  OSX should be working, as that is what much of this was developed on.  Try `npx trv run` on your mac and it should work.

**Comment by arciisine** [comment]
I've pushed out a fix, you will need to upgrade the yeoman generator (@travetto/generator-app), but I was able to successfully use the cli again on windows.  Let me know if this fixes your problem

**Comment by Enchiphobe** [comment]
Looks fixed. Thanks for the quick response!
