### ISSUE TITLE
npx travetto run in newly created travetto project

### ISSUE THREAD

**Issue by ZachRoberts25** [travetto/travetto#38]
```
Cannot find module '/Users/zach.roberts/projects/college-finder/node_modules/src/launch'
Require stack:
- /Users/zach.roberts/projects/college-finder/node_modules/@travetto/boot/src/register.js
- /Users/zach.roberts/projects/college-finder/node_modules/@travetto/boot/bin/init.js
- /Users/zach.roberts/projects/college-finder/node_modules/.bin/travetto
```

Using just travetto with globally installed works. My global version is `0.7.1-alpha.1`
project travetto cli version is `Latest version: 0.7.1-alpha.3`

**Comment by arciisine** [comment]
Werid, I'll take a look and get back to you, can you share the exact command you ran as well as some level of reproducible config?

**Comment by ZachRoberts25** [comment]
this command `npx travetto run rest` produces the error.  `travetto run rest` is fine

**Comment by ZachRoberts25** [comment]
works after reinstalling dependencies, dunno
