### ISSUE TITLE
Mongodb specify SSL

### ISSUE THREAD

**Issue by ZachRoberts25** [travetto/travetto#41]
So, this is a fun one, in order to use Amazons document db, they configure it to run over ssl, which requires passing options to the mongo client on creation.  Currently you are passing all options in the URL, by checking out there guide it looks like we have to pass opts as a secondary param when creating the client.

https://docs.aws.amazon.com/documentdb/latest/developerguide/connect.html

Let me know what you think.  This is probably going to be a common use case for those using mongo/aws

**Comment by arciisine** [comment]
The secondary options can be passed in the options object, will get added as key/value elements to the url.

https://github.com/travetto/travetto/blob/master/module/model-mongo/src/config.ts

What is currently not supported is the ability to pass username/password to the config url and I will be doing a release for that.

**Comment by arciisine** [comment]
Also, spoke a little too soon.  Looking at the nodejs examples, I see what else should be added, I will need to figure out exactly what the best way of handling that is.  At a minimum you can create your own config object that extends mongomodelconfig and you will just need wire that in as the config of choice.

**Comment by ZachRoberts25** [comment]
Not sure what you mean?  I could technically extend `MongoModelSource` and return that from the config and override the functions to do what I want, but also seems like this should be built in regardless.  Especially if you want to use AWS.

**Comment by arciisine** [comment]
There were two parts to the config (url parameters, and client options).  The url parameters are controllable, but the client options will need a code release.  I'm rewriting a bunch of it now to accommodate the AWS (and SSL/authenticated) flow better.  Should get a release tonight.

**Comment by arciisine** [comment]
This should also be in the latest release (as of this morning).

**Comment by ZachRoberts25** [comment]
testing this out but it looks legit for what I need, thank you kindly

**Comment by arciisine** [comment]
Closing as it should be working now.
