### ISSUE TITLE
ES version bump requires ES 7.x

### ISSUE THREAD

**Issue by ZachRoberts25** [travetto/travetto#45]
what I have noticed so far is that the updatePartial function is broken.  Looks like you bumped the ES version of the node package which now requires es 7.x.  That is not available in homebrew so maybe its a little premature for the upgrade?  Let me know what you want to do.  I can probably manually install es through docker as well if you think thats the right path, but I don't think it makes sense to force people onto a version of ES that isn't supported by brew

**Comment by ZachRoberts25** [comment]
As an aside tried using es 7.x and ran into a whole bunch of new issues.  I think downgraded the elasticsearchjs version is the way go

**Comment by arciisine** [comment]
i should have bumped it back to es 6.  I'm using 6.8 locally, and everything seems to be happy.  The es client upgraded and caused some problems so I had to pin the version.  The new client I haven't dealt with yet, but the lack of typings is making me less than comfortable.

**Comment by ZachRoberts25** [comment]
ok I had the latest travetto pulled, and the updatePartial was failing.  I checked the es version in model-elasticsearch and it was 16.x, I believe it needs to be 15.x

**Comment by arciisine** [comment]
I'll double check to make sure there are unit tests partial update.

**Comment by arciisine** [comment]
I have elasticsearch client 16.3.0  against elasticsearch 6.8 and the tests are passing (including those for partial update).  What version of elasticsearch server are you running.  This could potentially be a minor revision issue in elasticsearch.

**Comment by ZachRoberts25** [comment]
I am running 6.8 for es as well.

```"[invalid_type_name_exception] Document mapping type name can't start with '_', found: [_update]"```
is the error when I try go run `updateAllByQuery`

**Comment by ZachRoberts25** [comment]
actually this is for all update calls, I dropped the indexes in es and am still getting same issue

**Comment by ZachRoberts25** [comment]
I am dummy, I had to explictly set the API version to 6.8 in the `ElasticsearchModelConfig`.  Closing
