### ISSUE TITLE
Partial Update script on field that is an object fails if object is undefined

### ISSUE THREAD

**Issue by ZachRoberts25** [travetto/travetto#48]
given 
```
export class Address {
  name?: string;
  street1: string;
  city: string;
  state: string;
  zip: string;
  country?: string;
  @Telephone()
  phone?: string;
  validate?: boolean;
}
```

```
export class User extends BaseModel {
  address?: Address;
}
```

if I create a user with an undefined address which would be valid, I can't then call updatePartial to prefill the address, a null pointer is thrown.  The script that is generated assumes that address is already set which is not the case.

**Comment by arciisine** [comment]
Should be resolved by #49
