### ISSUE TITLE
Suggest Entities in 1.0 returns docs with _id

### ISSUE THREAD

**Issue by ZachRoberts25** [travetto/travetto#59]
looks like its missing `postLoad` ?

**Comment by arciisine** [comment]
The goal was to keep that the same. Let me take a look

**Comment by ZachRoberts25** [comment]
any update on this?  Still hoping to update to 1.0

**Comment by ZachRoberts25** [comment]
Also I can't seem to stay on version 6.x of elasticsearch.  There is not way for me to define that.  I am getting this error from what I think is that fact that it is expecting 7.x

`{"message":"mapper_parsing_exception","status":400,"type":"ResponseError"}`

**Comment by ZachRoberts25** [comment]
above error is actually related to cache model updates

**Comment by ZachRoberts25** [comment]
```"Numeric value (1567692187628) out of range of int
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@1a7e4ffb; line: 1, column: 68]"```

**Comment by arciisine** [comment]
I should have some bandwidth soon to take a look at this tonight.

**Comment by arciisine** [comment]
Fix has been pushed.
