### ISSUE TITLE
Stop logging on certain routes

### ISSUE THREAD

**Issue by ZachRoberts25** [travetto/travetto#60]
This may be a weird request, but could also see it being useful in general.  So our app has a health check endpoint, it would be great to not clutter the logs with the requests to the health check endpoint, but there is no way to tap into the route logs to stop it from happening.  Do you have thoughts on this ?

**Comment by arciisine** [comment]
Great idea. Let me think about it.  Right now the logger can be filtered on
patterns.  We could make the path a part of that. Or could do it through a
decorator.  I'll get back to you.

**Comment by ZachRoberts25** [comment]
Any updates on this?  I can take a stab at it if you want.  Would be reeally helpful for filtering out the healthchecks

**Comment by arciisine** [comment]
I think I have a solution, will send out a PR tonight

**Comment by arciisine** [comment]
PR is up for feedback. https://github.com/travetto/travetto/pull/63

**Comment by arciisine** [comment]
Code has been released
