### ISSUE TITLE
Route Log Filter doesn't account for Controller path

### ISSUE THREAD

**Issue by ZachRoberts25** [travetto/travetto#64]
it only looks at the sub path after your controller path, we would probably want it to examine the entire path, not just the sub path defined on the method

**Comment by arciisine** [comment]
Let me double check on that.  It should be at that level so I probably
missed it

**Comment by arciisine** [comment]
Okay, so definitely a gap, and to keep it performant, needed to update the syntax.

You can now specify in the form:
```yaml
rest.logRoutes.{deny|allow}:
  - '/'
  - '/controller1'
  - '/controller1:*'
  - '/controller2:/path'
  - '/controller3:/path/*` 
```

**Comment by arciisine** [comment]
Let me know if this is working for you

**Comment by ZachRoberts25** [comment]
working for us, thank you
