### ISSUE TITLE
Won't run inside kubernetes deployment

### ISSUE THREAD

**Issue by ZachRoberts25** [travetto/travetto#65]
Figured out most of whats going on, but the travetto app is just stopping after 

`2019-10-02T15:10:49.674Z debug [@trv:compiler/presence: 96] Watching files 83`

and won't continue on.  Related to bindAddress or cors ?  I am not totally sure tbh.

**Comment by ZachRoberts25** [comment]
if you have time at some point to debug, hit me up

**Comment by arciisine** [comment]
Sure. Btw that shouldn't be watching inside of the container.  Also try
changing the log level to trace

**Comment by ZachRoberts25** [comment]
Alright, the default elasticsearch cluster for kubernetes comes with authentication.  There is currently no way to pass auth info to the elasticsearch model config. Can we expose that ?

**Comment by arciisine** [comment]
That should be exposed.  Let me find the docs

**Comment by ZachRoberts25** [comment]
I believe the functionality is exposed in the PR I opened up  https://github.com/travetto/travetto/pull/66

**Comment by arciisine** [comment]
Should be fixed
