### ISSUE TITLE
Define certain configs, and config properties as secrets so they are not printed in logs

### ISSUE THREAD

**Issue by ZachRoberts25** [travetto/travetto#67]
Probably a decorator on properties in a config class, and an input to the config decorator to define it as a secret.  Secrets should not be printed in the logs when travetto starts up

**Comment by arciisine** [comment]
Is this just for startup or logs in general.  Config/startup is pretty easy to mask.  Maybe we start there and explore other places.

**Comment by arciisine** [comment]
Fixed
