### ISSUE TITLE
Elasticsearch schema generation create mappings with field of type keyword

### ISSUE THREAD

**Issue by kenny-eai** [travetto/travetto#88]
Class annotated with @Model will generate elasticsearch mappings with each property with type of keyword. If you annotated properties with @Text it creates a subfield of type text. But when you search with Travetto's query structure, it uses keyword field therefore making everything case-sensitive even though you want it to be case-insensitive.

**Comment by arciisine** [comment]
Hey,  so this has been resolved in the later versions of the framework. Anything on 0.7.x and before will not have this functionality.
